In [ ]:
print("LORD JESUS LOVES YOU")

LORD JESUS LOVES YOU

# #Experiment 1:Methods for handling missing values

Import Dataset

In [ ]:
#Import data
import pandas as pd
data=pd.read_csv('winequality-red.csv')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
# Count the number of missing values in each column
print(data.isnull().sum())

fixed acidity           1
volatile acidity        1
citric acid             1
residual sugar          0
chlorides               0
free sulfur dioxide     1
total sulfur dioxide    1
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Drop the rows containing missing values

In [ ]:
# Drop any rows that contain missing values
data_dropped = data.dropna()

In [ ]:
# Verify that there are no missing values in the new dataset
print(data_dropped.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Mean Imputation

In [ ]:
#Import data
import pandas as pd
data = pd.read_csv('winequality-red.csv')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
print(data.isnull().sum())

fixed acidity           1
volatile acidity        1
citric acid             1
residual sugar          0
chlorides               0
free sulfur dioxide     1
total sulfur dioxide    1
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
# Impute missing values with the mean value of the column
data_mean = data.fillna(data.mean())

In [ ]:


# Verify that there are no missing values in the new dataset
print(data_mean.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Median Imputation

In [ ]:
#Import data
import pandas as pd
data = pd.read_csv('winequality-red.csv')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:

# Impute missing values with the median value of the column
data_median = data.fillna(data.median())
# Verify that there are no missing values in the new dataset
print(data_median.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Simple Imputer by Scikit learn

In [ ]:

#scikit-learn's
#SimpleImputer class, which provides different strategies for handling missing valu
#We will demonstrate how to use three different strategies:
#mean imputation, median imputation, and most frequent imputation.

In [ ]:
#Import data
import pandas as pd
data = pd.read_csv('winequality-red.csv')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
from sklearn.impute import SimpleImputer
# Create a SimpleImputer object with the mean strategy
mean_imputer = SimpleImputer(strategy='mean')
# Create a SimpleImputer object with the median strategy
median_imputer = SimpleImputer(strategy='median')
# Create a SimpleImputer object with the most frequent strategy
mode_imputer = SimpleImputer(strategy='most_frequent')
# Separate the target variable (quality) from the predictors (features)
X = data.drop('quality', axis=1)
y = data['quality']
# Fit the imputers to the data and transform the data
X_mean_imputed = mean_imputer.fit_transform(X)
X_median_imputed = median_imputer.fit_transform(X)
X_mode_imputed = mode_imputer.fit_transform(X)
# Verify that there are no missing values in the new datasets
print(pd.DataFrame(X_mean_imputed).isnull().sum())
print(pd.DataFrame(X_median_imputed).isnull().sum())
print(pd.DataFrame(X_mode_imputed).isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64

Error since the feature 'type' is categorical

In [1]:
import numpy as np

Drop Quality

In [ ]:
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4

Drop type

In [ ]:
from sklearn.impute import SimpleImputer
# Create a SimpleImputer object with the mean strategy
mean_imputer = SimpleImputer(strategy='mean')
# Create a SimpleImputer object with the median strategy
median_imputer = SimpleImputer(strategy='median')
# Create a SimpleImputer object with the most frequent strategy
mode_imputer = SimpleImputer(strategy='most_frequent')
# Separate the target variable (quality) from the predictors (features)
#X = X.drop('type', axis=1)

y = data['quality']
# Fit the imputers to the data and transform the data
X_mean_imputed = mean_imputer.fit_transform(X)
X_median_imputed = median_imputer.fit_transform(X)
X_mode_imputed = mode_imputer.fit_transform(X)
# Verify that there are no missing values in the new datasets
print(pd.DataFrame(X_mean_imputed).isnull().sum())
print(pd.DataFrame(X_median_imputed).isnull().sum())
print(pd.DataFrame(X_mode_imputed).isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64

In [ ]:
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
3,11.2,0.28,0.56,NaN,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,NaN,11.0,34.0,0.9978,3.51,0.56,9.4

In [ ]:
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,NaN,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,7.8,NaN,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
2,7.8,0.76,NaN,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
3,11.2,0.28,0.56,NaN,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,NaN,11.0,34.0,0.9978,3.51,0.56,9.4